-- =============================================================================
-- ShuleSoft Academy — Skills Assessment & Verification module schema
-- Target: PostgreSQL, schema "academy" of shulesoft2024. Re-runnable (IF NOT EXISTS).
-- Spec: lineshop_new_version/docs/skiild.md (§37). Candidate = academy.users (linked
-- to talent.candidates by sid). Academy is the source of truth for credentials.
-- =============================================================================
SET client_min_messages TO WARNING;
SET search_path TO academy;

-- ---- taxonomy ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS skill_categories (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(150) NOT NULL,
    slug        varchar(160) NOT NULL,
    icon        varchar(80)  DEFAULT '',
    sort_order  integer      DEFAULT 0,
    status      integer      DEFAULT 1,
    created_at  timestamp    DEFAULT now(),
    updated_at  timestamp    DEFAULT now()
);

CREATE TABLE IF NOT EXISTS skills (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     integer,
    name            varchar(150) NOT NULL,
    slug            varchar(160) NOT NULL,
    description     text DEFAULT '',
    validity_months integer,                    -- nullable: null = never expires (§21)
    status          integer DEFAULT 1,
    created_at      timestamp DEFAULT now(),
    updated_at      timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS skill_levels (      -- 5 standardized levels (§4)
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(60) NOT NULL,
    slug        varchar(60) NOT NULL,
    rank        integer NOT NULL,
    description text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS skill_competencies ( -- competency framework (§9)
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id    integer NOT NULL,
    name        varchar(150) NOT NULL,
    description text DEFAULT '',
    weight      numeric(6,2) DEFAULT 0,          -- blueprint weight % (§8)
    is_critical integer DEFAULT 0,               -- critical competency floor (§17)
    sort_order  integer DEFAULT 0,
    status      integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS skill_competency_levels (  -- min standard per level (§17)
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competency_id  integer NOT NULL,
    skill_level_id integer NOT NULL,
    description    text DEFAULT '',
    minimum_score  numeric(6,2) DEFAULT 0
);

-- ---- assessments ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS assessments (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id         integer NOT NULL,
    skill_level_id   integer NOT NULL,
    title            varchar(200) NOT NULL,
    description      text DEFAULT '',
    duration_minutes integer DEFAULT 60,
    pass_score       numeric(6,2) DEFAULT 70,        -- overall % (§15/§17)
    critical_min     numeric(6,2) DEFAULT 60,        -- floor for critical competencies (§17)
    total_questions  integer DEFAULT 0,
    max_attempts     integer DEFAULT 1,              -- per purchase (§23)
    cooldown_days    integer DEFAULT 7,              -- retake cooldown (§23)
    version          integer DEFAULT 1,              -- governance versioning (§43)
    status           varchar(20) DEFAULT 'draft',    -- draft|published|retired
    created_at       timestamp DEFAULT now(),
    updated_at       timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assessment_sections (      -- Knowledge/Situational/Practical (§7)
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id integer NOT NULL,
    name          varchar(120) NOT NULL,
    type          varchar(30) DEFAULT 'knowledge',    -- knowledge|situational|practical|structured
    num_questions integer DEFAULT 0,
    sort_order    integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS assessment_questions (     -- bank (§10–§13)
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id   integer,                          -- null = shared bank
    section_id      integer,
    skill_id        integer,
    competency_id   integer,
    skill_level_id  integer,
    question_type   varchar(30) NOT NULL,             -- single|multiple|truefalse|matching|ordering|numerical|short_text|long_text|file|practical
    question_text   text NOT NULL,
    difficulty      varchar(20) DEFAULT 'medium',     -- easy|medium|hard|expert (§13)
    points          numeric(6,2) DEFAULT 1,
    time_seconds    integer DEFAULT 0,
    explanation     text DEFAULT '',
    marking_criteria text DEFAULT '',
    expected_answer text DEFAULT '',
    numeric_answer  numeric(14,4),                    -- for numerical type
    numeric_tolerance numeric(14,4) DEFAULT 0,
    reference_notes text DEFAULT '',
    tags            varchar(255) DEFAULT '',
    ai_generated    integer DEFAULT 0,
    status          varchar(20) DEFAULT 'draft',      -- draft|reviewed|approved|published (§14)
    is_active       integer DEFAULT 1,
    created_at      timestamp DEFAULT now(),
    updated_at      timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assessment_question_options (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id   integer NOT NULL,
    option_text   text NOT NULL,
    is_correct    integer DEFAULT 0,
    score         numeric(6,2) DEFAULT 0,             -- partial credit / SJT weighting
    match_key     varchar(120) DEFAULT '',            -- matching pairs
    correct_order integer DEFAULT 0,                  -- ordering
    sort_order    integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS assessment_rubrics (        -- practical rubric criteria (§30)
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id integer,
    question_id   integer,
    competency_id integer,
    criterion     varchar(200) NOT NULL,
    description   text DEFAULT '',
    max_score     numeric(6,2) DEFAULT 10,
    weight        numeric(6,2) DEFAULT 0,
    sort_order    integer DEFAULT 0
);

-- ---- pricing (§6) -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS assessment_products (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id       integer NOT NULL,
    skill_level_id integer NOT NULL,
    assessment_id  integer,
    price          numeric(12,2) DEFAULT 0,
    currency       varchar(10) DEFAULT 'TZS',
    retake_price   numeric(12,2),
    active         integer DEFAULT 1,
    effective_from date,
    effective_until date,
    created_at     timestamp DEFAULT now()
);

-- ---- payments (mirrors talent PaymentService/order, §37) --------------------
CREATE TABLE IF NOT EXISTS assessment_payments (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id  integer NOT NULL,                    -- academy.users.id
    sid           integer,
    assessment_id integer NOT NULL,
    product_id    integer,
    invoice_id    varchar(120) DEFAULT '',             -- Safaribank billing invoice id
    amount        numeric(12,2) DEFAULT 0,
    currency      varchar(10) DEFAULT 'TZS',
    gateway       varchar(60) DEFAULT '',
    status        varchar(20) DEFAULT 'pending',       -- pending|awaiting|paid|failed
    paid_at       timestamp,
    created_at    timestamp DEFAULT now(),
    updated_at    timestamp DEFAULT now()
);

-- ---- attempts (§22) ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS assessment_attempts (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id       integer NOT NULL,
    sid                integer,
    assessment_id      integer NOT NULL,
    assessment_version integer DEFAULT 1,
    payment_id         integer,
    attempt_number     integer DEFAULT 1,
    started_at         timestamp,
    completed_at       timestamp,
    submitted_at       timestamp,
    expires_at         timestamp,                       -- started_at + duration (timer §27)
    score              numeric(6,2),
    result             varchar(30) DEFAULT 'in_progress', -- in_progress|passed|failed|lower_level|invalidated (§18)
    level_awarded      integer,                          -- skill_level_id actually demonstrated
    competency_scores  text DEFAULT '',                  -- json {competency_id: pct} (§16)
    integrity_status   varchar(20) DEFAULT 'clean',
    ip_address         varchar(60) DEFAULT '',
    device_info        text DEFAULT '',
    needs_review       integer DEFAULT 0,
    created_at         timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assessment_attempt_answers (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id    integer NOT NULL,
    question_id   integer NOT NULL,
    competency_id integer,
    answer        text DEFAULT '',                      -- json/text (option ids, text, numeric)
    is_correct    integer,
    score         numeric(6,2),
    max_score     numeric(6,2) DEFAULT 0,
    auto_scored   integer DEFAULT 0,
    changes_count integer DEFAULT 0,                    -- integrity (§25)
    answered_at   timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assessment_submissions (     -- practical file uploads (§7/§29)
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id  integer NOT NULL,
    question_id integer,
    file_path   varchar(255) DEFAULT '',
    notes       text DEFAULT '',
    created_at  timestamp DEFAULT now()
);

-- ---- review queue (§29–§30) -------------------------------------------------
CREATE TABLE IF NOT EXISTS assessment_reviews (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id  integer NOT NULL,
    reviewer_id integer,
    status      varchar(20) DEFAULT 'pending',          -- pending|in_review|approved|rejected|needs_revision
    notes       text DEFAULT '',
    assigned_at timestamp,
    reviewed_at timestamp,
    created_at  timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assessment_review_scores (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id  integer NOT NULL,
    rubric_id  integer,
    question_id integer,
    score      numeric(6,2) DEFAULT 0,
    comment    text DEFAULT ''
);

-- ---- results & credentials (§37/§19) ----------------------------------------
CREATE TABLE IF NOT EXISTS candidate_skill_results (    -- bridge to Talent (§37)
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id      integer NOT NULL,
    sid               integer,
    skill_id          integer NOT NULL,
    skill_level_id    integer NOT NULL,
    assessment_id     integer NOT NULL,
    attempt_id        integer NOT NULL,
    overall_score     numeric(6,2) DEFAULT 0,
    competency_scores text DEFAULT '',
    status            varchar(20) DEFAULT 'verified',    -- verified|not_verified|lower_level
    verified_at       timestamp,
    expires_at        timestamp,
    credential_id     integer,
    created_at        timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS skill_credentials (          -- credential (§19–§21)
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id       integer NOT NULL,
    sid                integer,
    skill_id           integer NOT NULL,
    skill_level_id     integer NOT NULL,
    result_id          integer,
    credential_number  varchar(60) NOT NULL DEFAULT '',
    verification_token varchar(80) NOT NULL,
    overall_score      numeric(6,2) DEFAULT 0,
    assessment_version integer DEFAULT 1,
    issued_at          timestamp DEFAULT now(),
    expires_at         timestamp,
    status             varchar(20) DEFAULT 'active',     -- active|expired|revoked|suspended|superseded (§20)
    revoked_reason     text DEFAULT '',
    created_at         timestamp DEFAULT now()
);

-- ---- indexes ----------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_skills_category        ON skills (category_id);
CREATE INDEX IF NOT EXISTS idx_competencies_skill     ON skill_competencies (skill_id);
CREATE INDEX IF NOT EXISTS idx_questions_assessment   ON assessment_questions (assessment_id);
CREATE INDEX IF NOT EXISTS idx_questions_bank         ON assessment_questions (skill_id, competency_id, skill_level_id, question_type);
CREATE INDEX IF NOT EXISTS idx_options_question       ON assessment_question_options (question_id);
CREATE INDEX IF NOT EXISTS idx_attempts_candidate     ON assessment_attempts (candidate_id, assessment_id);
CREATE INDEX IF NOT EXISTS idx_answers_attempt        ON assessment_attempt_answers (attempt_id);
CREATE INDEX IF NOT EXISTS idx_results_candidate      ON candidate_skill_results (candidate_id, skill_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_credential_number ON skill_credentials (credential_number);
CREATE UNIQUE INDEX IF NOT EXISTS uq_credential_token  ON skill_credentials (verification_token);
CREATE INDEX IF NOT EXISTS idx_credentials_candidate  ON skill_credentials (candidate_id, status);
